name: insta_clone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  collection: ^1.18.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^6.0.3
  flutter_hooks: ^0.20.4
  font_awesome_flutter: ^10.6.0
  google_sign_in: ^6.2.1
  hooks_riverpod: ^2.4.9
  image: ^4.1.4
  image_picker: ^1.0.7
  intl: ^0.19.0
  lottie: ^3.0.0
  riverpod_annotation: ^2.3.3
  share_plus: ^7.2.1
  url_launcher: ^6.2.3
  uuid: ^4.3.3
  video_player: ^2.8.2
  video_thumbnail: ^0.5.3

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
  assets:
    - assets/animations/empty.json
    - assets/animations/loading.json
    - assets/animations/data_not_found.json
    - assets/animations/error.json
    - assets/animations/small_error.json
